services:
  postgres:
    image: postgres:18.1
    container_name: tasks_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test      
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  postgres_data: